// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectLoopbreaker.Infrastructure.Data;

#nullable disable

namespace ProjectLoopbreaker.Infrastructure.Migrations
{
    [DbContext(typeof(MediaLibraryDbContext))]
    [Migration("20260104202342_AddWebsiteArchiveFields")]
    partial class AddWebsiteArchiveFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaItemGenres", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("MediaItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaItemGenres", (string)null);
                });

            modelBuilder.Entity("MediaItemTopics", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("MediaItemId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("MediaItemTopics", (string)null);
                });

            modelBuilder.Entity("MixlistMediaItems", b =>
                {
                    b.Property<Guid>("MixlistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.HasKey("MixlistId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MixlistMediaItems", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OwnershipStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Rating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RelatedNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("MediaItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Highlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighlightUrl")
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)");

                    b.Property<DateTime?>("HighlightedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("character varying(2047)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Note")
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<int?>("ReadwiseBookId")
                        .HasColumnType("integer");

                    b.Property<int>("ReadwiseId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("character varying(2047)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<string>("Title")
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BookId");

                    b.HasIndex("Category");

                    b.HasIndex("HighlightedAt");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("ReadwiseBookId");

                    b.HasIndex("ReadwiseId")
                        .IsUnique();

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Mixlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Mixlists");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubePlaylistVideo", b =>
                {
                    b.Property<Guid>("YouTubePlaylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VideoPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("YouTubePlaylistId", "VideoId");

                    b.HasIndex("AddedAt");

                    b.HasIndex("Position");

                    b.HasIndex("VideoId");

                    b.ToTable("YouTubePlaylistVideo");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Article", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FullTextContent")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStarred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReaderSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publication")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReaderLocation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ReadingProgress")
                        .HasColumnType("integer");

                    b.Property<string>("ReadwiseDocumentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("WordCount")
                        .HasColumnType("integer");

                    b.HasIndex("Author");

                    b.HasIndex("IsArchived");

                    b.HasIndex("IsStarred");

                    b.HasIndex("Publication");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("ReaderLocation");

                    b.HasIndex("ReadwiseDocumentId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Book", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("ASIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("GoodreadsRating")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<string>>("GoodreadsTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ISBN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<DateTime?>("LastReadwiseSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MyReview")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("OriginalPublicationYear")
                        .HasColumnType("integer");

                    b.Property<bool>("PartOfSeries")
                        .HasColumnType("boolean");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ReadwiseBookId")
                        .HasColumnType("integer");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("integer");

                    b.HasIndex("ASIN");

                    b.HasIndex("Author");

                    b.HasIndex("DateRead");

                    b.HasIndex("ISBN");

                    b.HasIndex("OriginalPublicationYear");

                    b.HasIndex("YearPublished");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Movie", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Homepage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MpaaRating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TmdbBackdropPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("double precision");

                    b.HasIndex("Director");

                    b.HasIndex("ImdbId");

                    b.HasIndex("ReleaseYear");

                    b.HasIndex("TmdbId");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.PodcastEpisode", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("AudioLink")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DurationInSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("SeriesId");

                    b.ToTable("PodcastEpisodes", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.PodcastSeries", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalEpisodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasIndex("ExternalId");

                    b.HasIndex("IsSubscribed");

                    b.ToTable("PodcastSeries", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.TvShow", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentRating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Creator")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FirstAirYear")
                        .HasColumnType("integer");

                    b.Property<string>("Homepage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("LastAirYear")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfEpisodes")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfSeasons")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TmdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TmdbPosterPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("double precision");

                    b.HasIndex("Creator");

                    b.HasIndex("FirstAirYear");

                    b.HasIndex("LastAirYear");

                    b.HasIndex("TmdbId");

                    b.ToTable("TvShows", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Video", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LengthInSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentVideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VideoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ParentVideoId");

                    b.HasIndex("Platform");

                    b.HasIndex("VideoType");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Website", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("ArchiveStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ArchiveUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Domain")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publication")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RssFeedUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WaybackUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasIndex("Domain");

                    b.HasIndex("LastCheckedDate");

                    b.ToTable("Websites", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("ChannelExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CustomUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SubscriberCount")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadsPlaylistId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("VideoCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasIndex("ChannelExternalId")
                        .IsUnique();

                    b.HasIndex("LastSyncedAt");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("SubscriberCount");

                    b.ToTable("YouTubeChannels", (string)null);
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubePlaylist", b =>
                {
                    b.HasBaseType("ProjectLoopbreaker.Domain.Entities.BaseMediaItem");

                    b.Property<string>("ChannelExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedYouTubeChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaylistExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrivacyStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VideoCount")
                        .HasColumnType("integer");

                    b.HasIndex("LastSyncedAt");

                    b.HasIndex("LinkedYouTubeChannelId");

                    b.HasIndex("PlaylistExternalId")
                        .IsUnique();

                    b.HasIndex("PublishedAt");

                    b.ToTable("YouTubePlaylists");
                });

            modelBuilder.Entity("MediaItemGenres", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaItemTopics", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MixlistMediaItems", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Mixlist", null)
                        .WithMany()
                        .HasForeignKey("MixlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Highlight", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Article", "Article")
                        .WithMany("Highlights")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Book", "Book")
                        .WithMany("Highlights")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubePlaylistVideo", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Video", "Video")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.YouTubePlaylist", "YouTubePlaylist")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("YouTubePlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");

                    b.Navigation("YouTubePlaylist");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Article", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.Article", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Book", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Movie", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.Movie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.PodcastEpisode", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.PodcastEpisode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.PodcastSeries", "Series")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.PodcastSeries", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.PodcastSeries", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.TvShow", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.TvShow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Video", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.Video", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.Video", "ParentVideo")
                        .WithMany("Episodes")
                        .HasForeignKey("ParentVideoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Channel");

                    b.Navigation("ParentVideo");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Website", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.Website", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubePlaylist", b =>
                {
                    b.HasOne("ProjectLoopbreaker.Domain.Entities.BaseMediaItem", null)
                        .WithOne()
                        .HasForeignKey("ProjectLoopbreaker.Domain.Entities.YouTubePlaylist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", "LinkedYouTubeChannel")
                        .WithMany()
                        .HasForeignKey("LinkedYouTubeChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedYouTubeChannel");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Article", b =>
                {
                    b.Navigation("Highlights");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Book", b =>
                {
                    b.Navigation("Highlights");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.PodcastSeries", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.Video", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("PlaylistVideos");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubeChannel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ProjectLoopbreaker.Domain.Entities.YouTubePlaylist", b =>
                {
                    b.Navigation("PlaylistVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
