CREATE EXTENSION IF NOT EXISTS vector;


CREATE TABLE "FeatureFlags" (
    "Id" uuid NOT NULL,
    "Key" character varying(100) NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT FALSE,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_FeatureFlags" PRIMARY KEY ("Id")
);


CREATE TABLE "Genres" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);


CREATE TABLE "MediaItems" (
    "Id" uuid NOT NULL,
    "Title" character varying(500) NOT NULL,
    "MediaType" character varying(50) NOT NULL,
    "Link" character varying(2000),
    "Notes" text,
    "DateAdded" timestamp with time zone NOT NULL,
    "Status" character varying(50) NOT NULL,
    "DateCompleted" timestamp with time zone,
    "Rating" character varying(50),
    "OwnershipStatus" character varying(50),
    "Description" text,
    "RelatedNotes" text,
    "Thumbnail" character varying(2000),
    "EmbeddingGeneratedAt" timestamp with time zone,
    "EmbeddingModel" character varying(100),
    CONSTRAINT "PK_MediaItems" PRIMARY KEY ("Id")
);


CREATE TABLE "Mixlists" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Thumbnail" character varying(2000),
    "DateCreated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Mixlists" PRIMARY KEY ("Id")
);


CREATE TABLE "Notes" (
    "Id" uuid NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Title" character varying(500) NOT NULL,
    "Content" text,
    "Description" text,
    "VaultName" character varying(50) NOT NULL,
    "SourceUrl" character varying(2000),
    "Tags" jsonb NOT NULL,
    "NoteDate" timestamp with time zone,
    "DateImported" timestamp with time zone NOT NULL,
    "LastSyncedAt" timestamp with time zone,
    "ContentHash" character varying(64),
    "AiDescription" text,
    "AiDescriptionGeneratedAt" timestamp with time zone,
    "IsDescriptionManual" boolean NOT NULL DEFAULT FALSE,
    "EmbeddingGeneratedAt" timestamp with time zone,
    "EmbeddingModel" character varying(100),
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
);


CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" character varying(500) NOT NULL,
    "UserId" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByToken" character varying(500),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
);


CREATE TABLE "Topics" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Topics" PRIMARY KEY ("Id")
);


CREATE TABLE "Articles" (
    "Id" uuid NOT NULL,
    "FullTextContent" text,
    "ContentStoragePath" character varying(500),
    "IsArchived" boolean NOT NULL DEFAULT FALSE,
    "IsStarred" boolean NOT NULL DEFAULT FALSE,
    "LastSyncDate" timestamp with time zone,
    "Author" character varying(200),
    "Publication" character varying(200),
    "PublicationDate" timestamp with time zone,
    "ReadingProgress" integer,
    "WordCount" integer,
    "ReadwiseDocumentId" character varying(100),
    "ReaderLocation" character varying(50),
    "LastReaderSync" timestamp with time zone,
    "SyncStatus" integer NOT NULL,
    CONSTRAINT "PK_Articles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Articles_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Books" (
    "Id" uuid NOT NULL,
    "Author" character varying(300) NOT NULL,
    "ISBN" character varying(17),
    "ASIN" character varying(20),
    "Format" character varying(50) NOT NULL,
    "PartOfSeries" boolean NOT NULL,
    "GoodreadsRating" numeric,
    "AverageRating" numeric,
    "YearPublished" integer,
    "OriginalPublicationYear" integer,
    "DateRead" timestamp with time zone,
    "MyReview" character varying(10000),
    "Publisher" character varying(500),
    "GoodreadsTags" jsonb NOT NULL,
    "ReadwiseBookId" integer,
    "LastReadwiseSync" timestamp with time zone,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Documents" (
    "Id" uuid NOT NULL,
    "PaperlessId" integer,
    "OriginalFileName" character varying(500),
    "ArchiveSerialNumber" character varying(100),
    "DocumentType" character varying(200),
    "Correspondent" character varying(200),
    "OcrContent" text,
    "DocumentDate" timestamp with time zone,
    "PageCount" integer,
    "FileType" character varying(20),
    "FileSizeBytes" bigint,
    "PaperlessTagsCsv" text,
    "CustomFieldsJson" text,
    "LastPaperlessSync" timestamp with time zone,
    "PaperlessUrl" character varying(2000),
    "IsArchived" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MediaItemGenres" (
    "MediaItemId" uuid NOT NULL,
    "GenreId" uuid NOT NULL,
    CONSTRAINT "PK_MediaItemGenres" PRIMARY KEY ("MediaItemId", "GenreId"),
    CONSTRAINT "FK_MediaItemGenres_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genres" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaItemGenres_MediaItems_MediaItemId" FOREIGN KEY ("MediaItemId") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Movies" (
    "Id" uuid NOT NULL,
    "Director" character varying(100),
    "Cast" character varying(500),
    "ReleaseYear" integer,
    "RuntimeMinutes" integer,
    "MpaaRating" character varying(50),
    "ImdbId" character varying(20),
    "TmdbId" character varying(20),
    "TmdbRating" double precision,
    "TmdbBackdropPath" character varying(2000),
    "Tagline" character varying(1000),
    "Homepage" character varying(2000),
    "OriginalLanguage" character varying(10),
    "OriginalTitle" character varying(500),
    CONSTRAINT "PK_Movies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Movies_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PodcastSeries" (
    "Id" uuid NOT NULL,
    "Publisher" character varying(500),
    "ExternalId" character varying(200),
    "IsSubscribed" boolean NOT NULL DEFAULT FALSE,
    "LastSyncDate" timestamp with time zone,
    "TotalEpisodes" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_PodcastSeries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PodcastSeries_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TvShows" (
    "Id" uuid NOT NULL,
    "Creator" character varying(100),
    "Cast" character varying(500),
    "FirstAirYear" integer,
    "LastAirYear" integer,
    "NumberOfSeasons" integer,
    "NumberOfEpisodes" integer,
    "ContentRating" character varying(50),
    "TmdbId" character varying(20),
    "TmdbRating" double precision,
    "TmdbPosterPath" character varying(2000),
    "Tagline" character varying(1000),
    "Homepage" character varying(2000),
    "OriginalLanguage" character varying(10),
    "OriginalName" character varying(500),
    CONSTRAINT "PK_TvShows" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TvShows_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Websites" (
    "Id" uuid NOT NULL,
    "RssFeedUrl" character varying(2000),
    "LastCheckedDate" timestamp with time zone,
    "Domain" character varying(200),
    "Author" character varying(200),
    "Publication" character varying(200),
    "ArchiveUrl" character varying(2000),
    "ArchivedAt" timestamp with time zone,
    "ArchiveStatus" character varying(50),
    "WaybackUrl" character varying(2000),
    CONSTRAINT "PK_Websites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Websites_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "YouTubeChannels" (
    "Id" uuid NOT NULL,
    "ChannelExternalId" character varying(100) NOT NULL,
    "CustomUrl" character varying(200),
    "SubscriberCount" bigint,
    "VideoCount" bigint,
    "ViewCount" bigint,
    "UploadsPlaylistId" character varying(100),
    "Country" character varying(10),
    "PublishedAt" timestamp with time zone,
    "LastSyncedAt" timestamp with time zone,
    CONSTRAINT "PK_YouTubeChannels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_YouTubeChannels_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MixlistMediaItems" (
    "MixlistId" uuid NOT NULL,
    "MediaItemId" uuid NOT NULL,
    CONSTRAINT "PK_MixlistMediaItems" PRIMARY KEY ("MixlistId", "MediaItemId"),
    CONSTRAINT "FK_MixlistMediaItems_MediaItems_MediaItemId" FOREIGN KEY ("MediaItemId") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MixlistMediaItems_Mixlists_MixlistId" FOREIGN KEY ("MixlistId") REFERENCES "Mixlists" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MediaItemNotes" (
    "MediaItemId" uuid NOT NULL,
    "NoteId" uuid NOT NULL,
    "LinkedAt" timestamp with time zone NOT NULL,
    "LinkDescription" character varying(500),
    CONSTRAINT "PK_MediaItemNotes" PRIMARY KEY ("MediaItemId", "NoteId"),
    CONSTRAINT "FK_MediaItemNotes_MediaItems_MediaItemId" FOREIGN KEY ("MediaItemId") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaItemNotes_Notes_NoteId" FOREIGN KEY ("NoteId") REFERENCES "Notes" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MediaItemTopics" (
    "MediaItemId" uuid NOT NULL,
    "TopicId" uuid NOT NULL,
    CONSTRAINT "PK_MediaItemTopics" PRIMARY KEY ("MediaItemId", "TopicId"),
    CONSTRAINT "FK_MediaItemTopics_MediaItems_MediaItemId" FOREIGN KEY ("MediaItemId") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaItemTopics_Topics_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topics" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Highlights" (
    "Id" uuid NOT NULL,
    "ReadwiseId" integer NOT NULL,
    "Text" character varying(8191) NOT NULL,
    "Note" character varying(8191),
    "Title" character varying(511),
    "Author" character varying(1024),
    "Category" character varying(50),
    "SourceUrl" character varying(2047),
    "ImageUrl" character varying(2047),
    "HighlightUrl" character varying(4095),
    "Location" integer,
    "LocationType" character varying(50),
    "HighlightedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "Tags" character varying(1000),
    "ArticleId" uuid,
    "BookId" uuid,
    "ReadwiseBookId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SourceType" character varying(64),
    "IsFavorite" boolean NOT NULL DEFAULT FALSE,
    "Color" character varying(50),
    "Metadata" jsonb,
    CONSTRAINT "PK_Highlights" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Highlights_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Highlights_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE SET NULL
);


CREATE TABLE "PodcastEpisodes" (
    "Id" uuid NOT NULL,
    "SeriesId" uuid NOT NULL,
    "AudioLink" character varying(2000),
    "ReleaseDate" timestamp with time zone,
    "DurationInSeconds" integer NOT NULL DEFAULT 0,
    "EpisodeNumber" integer,
    "SeasonNumber" integer,
    "ExternalId" character varying(200),
    "Publisher" character varying(500),
    CONSTRAINT "PK_PodcastEpisodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PodcastEpisodes_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PodcastEpisodes_PodcastSeries_SeriesId" FOREIGN KEY ("SeriesId") REFERENCES "PodcastSeries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Videos" (
    "Id" uuid NOT NULL,
    "VideoType" character varying(50) NOT NULL,
    "ParentVideoId" uuid,
    "Platform" character varying(100) NOT NULL,
    "ChannelId" uuid,
    "LengthInSeconds" integer NOT NULL DEFAULT 0,
    "ExternalId" character varying(200),
    CONSTRAINT "PK_Videos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Videos_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Videos_Videos_ParentVideoId" FOREIGN KEY ("ParentVideoId") REFERENCES "Videos" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Videos_YouTubeChannels_ChannelId" FOREIGN KEY ("ChannelId") REFERENCES "YouTubeChannels" ("Id") ON DELETE SET NULL
);


CREATE TABLE "YouTubePlaylists" (
    "Id" uuid NOT NULL,
    "PlaylistExternalId" character varying(100) NOT NULL,
    "ChannelExternalId" character varying(100),
    "LinkedYouTubeChannelId" uuid,
    "VideoCount" integer,
    "PublishedAt" timestamp with time zone,
    "LastSyncedAt" timestamp with time zone,
    "PrivacyStatus" character varying(50),
    CONSTRAINT "PK_YouTubePlaylists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_YouTubePlaylists_MediaItems_Id" FOREIGN KEY ("Id") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YouTubePlaylists_YouTubeChannels_LinkedYouTubeChannelId" FOREIGN KEY ("LinkedYouTubeChannelId") REFERENCES "YouTubeChannels" ("Id") ON DELETE SET NULL
);


CREATE TABLE "YouTubePlaylistVideo" (
    "YouTubePlaylistId" uuid NOT NULL,
    "VideoId" uuid NOT NULL,
    "Position" integer,
    "AddedAt" timestamp with time zone NOT NULL,
    "VideoPublishedAt" timestamp with time zone,
    CONSTRAINT "PK_YouTubePlaylistVideo" PRIMARY KEY ("YouTubePlaylistId", "VideoId"),
    CONSTRAINT "FK_YouTubePlaylistVideo_Videos_VideoId" FOREIGN KEY ("VideoId") REFERENCES "Videos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YouTubePlaylistVideo_YouTubePlaylists_YouTubePlaylistId" FOREIGN KEY ("YouTubePlaylistId") REFERENCES "YouTubePlaylists" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Articles_Author" ON "Articles" ("Author");


CREATE INDEX "IX_Articles_IsArchived" ON "Articles" ("IsArchived");


CREATE INDEX "IX_Articles_IsStarred" ON "Articles" ("IsStarred");


CREATE INDEX "IX_Articles_Publication" ON "Articles" ("Publication");


CREATE INDEX "IX_Articles_PublicationDate" ON "Articles" ("PublicationDate");


CREATE INDEX "IX_Articles_ReaderLocation" ON "Articles" ("ReaderLocation");


CREATE INDEX "IX_Articles_ReadwiseDocumentId" ON "Articles" ("ReadwiseDocumentId");


CREATE INDEX "IX_Books_ASIN" ON "Books" ("ASIN");


CREATE INDEX "IX_Books_Author" ON "Books" ("Author");


CREATE INDEX "IX_Books_DateRead" ON "Books" ("DateRead");


CREATE INDEX "IX_Books_ISBN" ON "Books" ("ISBN");


CREATE INDEX "IX_Books_OriginalPublicationYear" ON "Books" ("OriginalPublicationYear");


CREATE INDEX "IX_Books_YearPublished" ON "Books" ("YearPublished");


CREATE INDEX "IX_Documents_Correspondent" ON "Documents" ("Correspondent");


CREATE INDEX "IX_Documents_DocumentDate" ON "Documents" ("DocumentDate");


CREATE INDEX "IX_Documents_DocumentType" ON "Documents" ("DocumentType");


CREATE INDEX "IX_Documents_FileType" ON "Documents" ("FileType");


CREATE INDEX "IX_Documents_IsArchived" ON "Documents" ("IsArchived");


CREATE INDEX "IX_Documents_PaperlessId" ON "Documents" ("PaperlessId");


CREATE UNIQUE INDEX "IX_FeatureFlags_Key" ON "FeatureFlags" ("Key");


CREATE UNIQUE INDEX "IX_Genres_Name" ON "Genres" ("Name");


CREATE INDEX "IX_Highlights_ArticleId" ON "Highlights" ("ArticleId");


CREATE INDEX "IX_Highlights_BookId" ON "Highlights" ("BookId");


CREATE INDEX "IX_Highlights_Category" ON "Highlights" ("Category");


CREATE INDEX "IX_Highlights_HighlightedAt" ON "Highlights" ("HighlightedAt");


CREATE INDEX "IX_Highlights_IsFavorite" ON "Highlights" ("IsFavorite");


CREATE INDEX "IX_Highlights_ReadwiseBookId" ON "Highlights" ("ReadwiseBookId");


CREATE UNIQUE INDEX "IX_Highlights_ReadwiseId" ON "Highlights" ("ReadwiseId");


CREATE INDEX "IX_MediaItemGenres_GenreId" ON "MediaItemGenres" ("GenreId");


CREATE INDEX "IX_MediaItemNotes_LinkedAt" ON "MediaItemNotes" ("LinkedAt");


CREATE INDEX "IX_MediaItemNotes_NoteId" ON "MediaItemNotes" ("NoteId");


CREATE INDEX "IX_MediaItemTopics_TopicId" ON "MediaItemTopics" ("TopicId");


CREATE INDEX "IX_MixlistMediaItems_MediaItemId" ON "MixlistMediaItems" ("MediaItemId");


CREATE INDEX "IX_Movies_Director" ON "Movies" ("Director");


CREATE INDEX "IX_Movies_ImdbId" ON "Movies" ("ImdbId");


CREATE INDEX "IX_Movies_ReleaseYear" ON "Movies" ("ReleaseYear");


CREATE INDEX "IX_Movies_TmdbId" ON "Movies" ("TmdbId");


CREATE INDEX "IX_Notes_DateImported" ON "Notes" ("DateImported");


CREATE INDEX "IX_Notes_IsDescriptionManual" ON "Notes" ("IsDescriptionManual");


CREATE INDEX "IX_Notes_LastSyncedAt" ON "Notes" ("LastSyncedAt");


CREATE INDEX "IX_Notes_VaultName" ON "Notes" ("VaultName");


CREATE UNIQUE INDEX "IX_Notes_VaultName_Slug" ON "Notes" ("VaultName", "Slug");


CREATE INDEX "IX_PodcastEpisodes_ExternalId" ON "PodcastEpisodes" ("ExternalId");


CREATE INDEX "IX_PodcastEpisodes_ReleaseDate" ON "PodcastEpisodes" ("ReleaseDate");


CREATE INDEX "IX_PodcastEpisodes_SeriesId" ON "PodcastEpisodes" ("SeriesId");


CREATE INDEX "IX_PodcastSeries_ExternalId" ON "PodcastSeries" ("ExternalId");


CREATE INDEX "IX_PodcastSeries_IsSubscribed" ON "PodcastSeries" ("IsSubscribed");


CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");


CREATE INDEX "IX_RefreshTokens_IsRevoked" ON "RefreshTokens" ("IsRevoked");


CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE UNIQUE INDEX "IX_Topics_Name" ON "Topics" ("Name");


CREATE INDEX "IX_TvShows_Creator" ON "TvShows" ("Creator");


CREATE INDEX "IX_TvShows_FirstAirYear" ON "TvShows" ("FirstAirYear");


CREATE INDEX "IX_TvShows_LastAirYear" ON "TvShows" ("LastAirYear");


CREATE INDEX "IX_TvShows_TmdbId" ON "TvShows" ("TmdbId");


CREATE INDEX "IX_Videos_ChannelId" ON "Videos" ("ChannelId");


CREATE INDEX "IX_Videos_ExternalId" ON "Videos" ("ExternalId");


CREATE INDEX "IX_Videos_ParentVideoId" ON "Videos" ("ParentVideoId");


CREATE INDEX "IX_Videos_Platform" ON "Videos" ("Platform");


CREATE INDEX "IX_Videos_VideoType" ON "Videos" ("VideoType");


CREATE INDEX "IX_Websites_Domain" ON "Websites" ("Domain");


CREATE INDEX "IX_Websites_LastCheckedDate" ON "Websites" ("LastCheckedDate");


CREATE UNIQUE INDEX "IX_YouTubeChannels_ChannelExternalId" ON "YouTubeChannels" ("ChannelExternalId");


CREATE INDEX "IX_YouTubeChannels_LastSyncedAt" ON "YouTubeChannels" ("LastSyncedAt");


CREATE INDEX "IX_YouTubeChannels_PublishedAt" ON "YouTubeChannels" ("PublishedAt");


CREATE INDEX "IX_YouTubeChannels_SubscriberCount" ON "YouTubeChannels" ("SubscriberCount");


CREATE INDEX "IX_YouTubePlaylists_LastSyncedAt" ON "YouTubePlaylists" ("LastSyncedAt");


CREATE INDEX "IX_YouTubePlaylists_LinkedYouTubeChannelId" ON "YouTubePlaylists" ("LinkedYouTubeChannelId");


CREATE UNIQUE INDEX "IX_YouTubePlaylists_PlaylistExternalId" ON "YouTubePlaylists" ("PlaylistExternalId");


CREATE INDEX "IX_YouTubePlaylists_PublishedAt" ON "YouTubePlaylists" ("PublishedAt");


CREATE INDEX "IX_YouTubePlaylistVideo_AddedAt" ON "YouTubePlaylistVideo" ("AddedAt");


CREATE INDEX "IX_YouTubePlaylistVideo_Position" ON "YouTubePlaylistVideo" ("Position");


CREATE INDEX "IX_YouTubePlaylistVideo_VideoId" ON "YouTubePlaylistVideo" ("VideoId");


